### ISSUE TITLE
Diagnostic Tool compatibility

### ISSUE THREAD

**Issue by danteciambella** [Sitecore/Sitecore-Configuration-Roles#15]
Hi @AlenPelin,
I have installed a Sitecore architecture (UAT (Standalone) + CM (Standalone) + CD1 (ContentDelivery) + CD2 (ContentDelivery)) using the Configuration Roles. For the moment everything is working fine. I would like to be more confident to have done the right stuff. 
Please is the Diagnostic Toll compatible with installation that use the Configuration Roles? If I try to use the SSPG package fron each role and test it using the Diagnostic Tool is the right way to procede?

Thanks a lot.
Dante.

**Comment by AlenPelin** [comment]
Hi Dante. 

Thanks for paying attention to the project. The request generally makes sense, but I'm afraid it is not possible because the only information we have about proper setup is the same excel file that is used as a source for configuration roles project. In this context using configuration roles is the same safe as configuring manually according to the documentation.

I know only the only way to check if configuration roles-based instance is configured correctly - use showconfig.aspx page to generate actual configuration XML and compare it with showconfig.aspx output of an instance that was configured manually according to the documentation. In general case in my personal opinion it is not reasonable investment of time. 

Hope that makes sense for you. 

Cheers, **Alen**

**Comment by danteciambella** [comment]
Alen thank you very much for your support.
I have understood thank you very much, I'm agree with you I don't think that I'll spent time comparing the two showconfig.aspx output.

I find the project very usefull for the Sitecore community, and if I had time I would like to contribute.

Regards I'll keep you updated if something strange will popup during our project evolution.
Dante.
